// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_FLAG_RCPPEXPORTS_H_GEN_
#define RCPP_FLAG_RCPPEXPORTS_H_GEN_

#include <RcppEigen.h>
#include <Rcpp.h>

namespace FLAG {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("FLAG", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("FLAG", "_FLAG_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in FLAG");
            }
        }
    }

    inline Rcpp::List test_pgbinary_cpp(const Eigen::MatrixXd& C, const Eigen::VectorXi& Y, const Eigen::MatrixXd& Cnv, int N_sample = 100, bool output_pi = false) {
        typedef SEXP(*Ptr_test_pgbinary_cpp)(SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_test_pgbinary_cpp p_test_pgbinary_cpp = NULL;
        if (p_test_pgbinary_cpp == NULL) {
            validateSignature("Rcpp::List(*test_pgbinary_cpp)(const Eigen::MatrixXd&,const Eigen::VectorXi&,const Eigen::MatrixXd&,int,bool)");
            p_test_pgbinary_cpp = (Ptr_test_pgbinary_cpp)R_GetCCallable("FLAG", "_FLAG_test_pgbinary_cpp");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_test_pgbinary_cpp(Shield<SEXP>(Rcpp::wrap(C)), Shield<SEXP>(Rcpp::wrap(Y)), Shield<SEXP>(Rcpp::wrap(Cnv)), Shield<SEXP>(Rcpp::wrap(N_sample)), Shield<SEXP>(Rcpp::wrap(output_pi)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::List >(rcpp_result_gen);
    }

}

#endif // RCPP_FLAG_RCPPEXPORTS_H_GEN_
