# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find indexes of the first r smallest elements in arrays based on Bubblesorting
#'
#' @param z Numeric vector, including elements to be sorted.
#' @param r Int, the number of the smallest elements.
#'
#' @return Integer vector of length r, indicating the indexes of the first r smallest elements.
#' @export
#'
#' @examples
#' z <- c(1,3,2)
#' r <- 2
#' which_minn_rcpp(z, r)
which_minn_rcpp <- function(z, r) {
    .Call(`_FLAG_which_minn_rcpp`, z, r)
}

