# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp sourceCpp
#' @importFrom BayesLogit rpg
#' @useDynLib FLAG, .registration=TRUE
NULL

#' @importFrom Rcpp sourceCpp
NULL

#' Predict labels on new samples with Polya-Gamma
#'
#' @param C A numeric matrix with dim(m,m), the self covariance matrix
#' in the training samples.
#' @param Y A numeric vector with length(m), count of the positive class.
#' @param Cnv A numeric matrix with dim(m_new,m), cross covariance matrix
#' between new sample and training sample.
#' @param N_sample An integer, the length of the Gibbs sampler chain.
#' @param output_pi Bool, whether or not to output pi_new, defaulting value is `FALSE`.
#'
#' @return `list(Y_pred)` if `output_pi=FALSE`, otherwise `list(pi_pred,Y_pred)`.
#' @export
#'
#' @examples
#' Z <- matrix(rnorm(3*3),3,3)
#' C <- Z%*%t(Z)
#' Y <- sample(c(0,1),3, replace=TRUE)
#' Cnv <- matrix(rnorm(5*3),5,3)
#' test_pgbinary_cpp(C, Y, Cnv)
test_pgbinary_cpp <- function(C, Y, Cnv, N_sample = 100L, output_pi = FALSE) {
    .Call(`_FLAG_test_pgbinary_cpp`, C, Y, Cnv, N_sample, output_pi)
}

#' Find indexes of the first r smallest elements in arrays based on Bubblesorting
#'
#' @param z Numeric vector, including elements to be sorted.
#' @param r Int, the number of the smallest elements.
#'
#' @return Integer vector of length r, indicating the indexes of the first r smallest elements.
#' @export
#'
#' @examples
#' z <- c(1,3,2)
#' r <- 2
#' which_minn_rcpp(z, r)
which_minn_rcpp <- function(z, r) {
    .Call(`_FLAG_which_minn_rcpp`, z, r)
}

